// Generated by CoffeeScript 1.6.1
(function() {
  var allComb, comb, extendArray, t;

  comb = function(x, ys) {
    var a, i, result, t, zs, _i, _ref;
    a = ys.slice(0);
    a.push([x]);
    result = [a];
    for (i = _i = 0, _ref = ys.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
      zs = ys.slice(0);
      t = zs[i].slice(0);
      t.push(x);
      zs[i] = t;
      result.push(zs);
    }
    return result;
  };

  extendArray = function(xs, ys) {
    return xs.push.apply(xs, ys);
  };

  allComb = function(items) {
    var ary, e, tail, ys, _i, _len;
    if (items.length === 1) {
      return [[items]];
    }
    tail = allComb(items.slice(1));
    ary = [];
    for (_i = 0, _len = tail.length; _i < _len; _i++) {
      e = tail[_i];
      ys = comb(items[0], e);
      extendArray(ary, ys);
    }
    return ary;
  };

  /*
  a = the1yuan([1,2,3,4,5])
  for e in a
    console.log e
  */


  t = allComb([1, 2, 3]);

  console.log(t);

}).call(this);
